# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Like
subtitle: Do one thing and do it well.
description: 不羁、懒散、喜欢幻想、热爱自由。
keywords: blog likezheng lastingman front-end coding 郑力可 博客 代码 前端
author: Like
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://lastingman.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

###################################################### plugin setting

## word counts
symbols_count_time:
  symbols: false
  time: true
  total_symbols: false
  total_time: true

## sitemap
sitemap:
  path: sitemap.xml

## next theme plugin
reading_progress:
  enable: true
  color: '#37c6c0'
  height: 4px

pangu: true

leancloud_visitors:
  enable: true
  app_id: BKchkFdEIsKU3vlVpVK7anzb-gzGzoHsz
  app_key: evfAMPDtAY6Sh1HKfjw162EV
  security: false
  betterPerformance: true

# rss
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub: # URL of the PubSubHubbub hubs (Leave it empty if you don't use it)
  content: false # (optional) set to 'true' to include the contents of the entire post in the feed.
  content_limit: 100 # (optional) Default length of post content used in summary. Only used, if content setting is false and no custom post description present.
  content_limit_delim: '。' # (optional) If content_limit is used to shorten post contents, only cut at the last occurrence of this delimiter before reaching the character limit. Not used by default.
  order_by: -date
  icon: /images/favicon/favicon-96x96.png

#################################################### custom config

# ipfs cdn tag plugin
gateway: 'https://likezheng.org/ipfs/'
