# darkmode: true

favicon:
  small: /images/favicon/favicon-16x16.png
  medium: /images/favicon/favicon-32x32.png
  apple_touch_icon: /images/favicon/apple-icon.png
  safari_pinned_tab: /images/favicon/logo.svg
  android_manifest: /images/favicon/manifest.json
  ms_browserconfig: /images/favicon/browserconfig.xml

read_more_btn: false

post_meta:
  item_text: false
  created_at: true
  updated_at:
    enable: false
    another_day: true
  categories: true

avatar:
  url: /images/avatar.png
  rounded: true
  rotated: false

menu_settings:
  icons: true
  badges: true
footer:
  since: 2019
  icon:
    name: fa fa-heart
    animated: true
    color: '#d81e06'
  powered: false
index_with_subtitle: true
exturl: true

scheme: Muse
# scheme: Mist
# scheme: Pisces
# scheme: Gemini

social:
  GitHub: https://github.com/lastingman || fab fa-github
  E-Mail: mailto:keithleaves@gmail.com || fa fa-envelope
social_icons:
  enable: true
  icons_only: true
  transition: true
tagcloud:
  min: 16
  max: 32

motion:
  enable: true
  async: true
  transition:
    # All available transition variants: https://theme-next.js.org/animate/
    post_block: fadeIn
    post_header: fadeInDown
    post_body: fadeInDown
    coll_header: fadeInLeft
    # Only for Pisces | Gemini.
    sidebar: fadeInUp
# Canvas ribbon
# For more information: https://github.com/hustcc/ribbon.js
canvas_ribbon:
  enable: false
  size: 300 # The width of the ribbon
  alpha: 0.4 # The transparency of the ribbon
  zIndex: -1 # The display level of the ribbon
# ##################### plugin settings
pangu: true
reading_progress:
  enable: true
  color: '#37c6c0'
  height: 4px
symbols_count_time:
  separated_meta: true
  item_text_post: true
  item_text_total: true
fancybox: true

tag_icon: true

disqus:
  enable: true
  shortname: likes-blog

leancloud_visitors:
  enable: true
  app_id: BKchkFdEIsKU3vlVpVK7anzb-gzGzoHsz
  app_key: evfAMPDtAY6Sh1HKfjw162EV

codeblock:
  # Code Highlight theme
  # All available themes: https://theme-next.js.org/highlight/
  prism:
    light: prism-darcula
    dark: prism-darcula
  # Add copy button on codeblock
  copy_button:
    enable: true
    # Available values: default | flat | mac
    style: flat

sidebar:
  # Sidebar Position.
  position: left
  #position: right

  # Manual define the sidebar width. If commented, will be default for:
  # Muse | Mist: 320
  # Pisces | Gemini: 240
  #width: 300

  # Sidebar Display (only for Muse | Mist), available values:
  #  - post    expand on posts automatically. Default.
  #  - always  expand for all pages automatically.
  #  - hide    expand only when click on the sidebar toggle icon.
  #  - remove  totally remove sidebar including sidebar toggle.
  display: hide

  # Sidebar padding in pixels.
  padding: 18
  # Sidebar offset from top menubar in pixels (only for Pisces | Gemini).
  offset: 12
